== Deploy NGINX Plus Ingress Controller with NAP to provide security for the Arcadia application

== Deployment Overview

In Module 1, we have already deployed the NGINX Ingress Controller, so
we will focus on configuring NGINX App Protect in this module. For the
complete installation of the NGINX Plus Ingress Controller, refer to the
link:https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/[Installation[official documentation]
with Manifests

At a high level, we will:


* Configure role-based access control (RBAC)
* Create the common Kubernetes resources
* Install the Ingress Controller with NGINX App Protect WAF
* Configure the NGINX App Protect WAF module
* Attach NAP Policy to the NGINX Ingress Controller’s Virtual Server


Clone the Ingress Controller repository and navigate to the deployments
folder by running the following commands:


[source,sh,role=execute]
----
git clone https://github.com/nginxinc/kubernetes-ingress.git --branch v3.0.1
cd kubernetes-ingress/deployments
----

== Configure role-based access control (RBAC)

In Module 1, we created a namespace and a service account for the
Ingress Controller, as well as a cluster role and a cluster role binding
for the service account. To use the App Protect WAF module, we need to
create the App Protect role and role binding by running the following
command:


[source,sh,role=execute]
----
oc apply -f rbac/ap-rbac.yaml
----

== Create the common Kubernetes resources

In Module 1, we created:

* a secret with a TLS certificate and a key for the default server in NGINX
* A config map for customizing NGINX configuration
* An IngressClass resource

No additional common resource is needed for the App Protect WAF module.

== Create Custom Resources

In Module 1, we created custom resource definitions for VirtualServer,
VirtualServerRoute, TransportServer, and Policy resources. To use the
App Protect WAF module, we need to create custom resource definitions
for APPolicy, APLogConf, and APUserSig. Run the following commands to
create these resources:

[source,sh,role=execute]
----
oc apply -f common/crds/appprotect.f5.com_aplogconfs.yaml
oc apply -f common/crds/appprotect.f5.com_appolicies.yaml
oc apply -f common/crds/appprotect.f5.com_apusersigs.yaml
----

== Update the Ingress Controller with NGINX App Protect WAF

We need to enable the App Protect module in the Ingress Controller

Paste the following into the ternminal

[source,sh,role=execute]
----
oc patch nginxingress my-nginx-ingress-controller \
  -n nginx-ingress \
  --type merge \
  -p '{"spec":{"controller":{"appprotect":{"enable":true}}}}'
----

To confirm the patch was applied correctly, run:

[source,sh,role=execute]
----
oc get nginxingress my-nginx-ingress -n nginx-ingress -o yaml | grep -A5 appprotect
----

[source,texinfo,subs="attributes"]
----
 $ oc get nginxingress my-nginx-ingress -n nginx-ingress -o yaml | grep -A5 appprotect
    appprotect:
      enable: true
    appprotectdos:
      debug: false
      enable: false
      maxDaemons: 0
      maxWorkers: 0
      memory: 0
 ----

[NOTE]
.Note
====
In your own deployments, make sure that you have pulled the Ingress Controller image with App
Protect. In this lab, we have already loaded the NGINX Plus image with App Protect to a local registry.
====

. After applying the patch, wait for the KIC pod to become available by running
the command:
+
[source,sh,role=execute]
----
oc get pod -n nginx-ingress --watch
----
. When it's ready, press `ctrl-c` to stop the watch.


== Configure the NGINX App Protect WAF module

Now, it is time to configure the Ingress Controller with CRD resources
(WAF policy, Log profile, Ingress routing ...)


. Execute the following commands to deploy the different resources. 

[source,sh,role=execute]
----
cd /home/lab-user/kubernetes-ingress/examples/custom-resources/app-protect-waf

oc apply -f syslog.yaml
oc apply -f ap-apple-uds.yaml
oc apply -f ap-dataguard-alarm-policy.yaml
oc apply -f ap-logconf.yaml
oc apply -f waf.yaml
----

Of the above commands, we focus on the following files:

[arabic]
. The `ap-dataguard-alarm-policy.yaml` file creates the WAF policy that
specifies the rules for protecting the application from layer 7 attacks.
It is recommended to customize this policy according to the specific
application requirements.

In this lab, we will proceed by disregarding the "apple_sigs" signature
set. Remove the subsequent lines from `ap-dataguard-alarm-policy.yaml`:


[source,sh,role=execute]
----
signature-requirements:
- tag: Fruits
signature-sets:
- name: apple_sigs
  block: true
  signatureSet:
    filter:
      tagValue: Fruits
      tagFilter: eq
----

If preferred, you can also accomplish this using the 'sed' command as
follows:


[source,sh,role=execute]
----
sed -i '/signature-requirements:/,/eq/d' ap-dataguard-alarm-policy.yaml
----

Once modified, your `ap-dataguard-alarm-policy.yaml` should resemble
this:

[source,sh]
----
$ cat -n ap-dataguard-alarm-policy.yaml 
     1  apiVersion: appprotect.f5.com/v1beta1
     2  kind: APPolicy
     3  metadata:
     4    name: dataguard-alarm
     5  spec:
     6    policy:
     7      applicationLanguage: utf-8
     8      blocking-settings:
     9        violations:
    10        - alarm: true
    11          block: false
    12          name: VIOL_DATA_GUARD
    13      data-guard:
    14        creditCardNumbers: true
    15        enabled: true
    16        enforcementMode: ignore-urls-in-list
    17        enforcementUrls: []
    18        lastCcnDigitsToExpose: 4
    19        lastSsnDigitsToExpose: 4
    20        maskData: true
    21        usSocialSecurityNumbers: true
    22      enforcementMode: blocking
    23      name: dataguard-alarm
    24      template:
    25        name: POLICY_TEMPLATE_NGINX_BASE
----

In the terminal window, paste the below, to reapply
the `ap-dataguard-alarm-policy.yaml` config.

[source,sh,role=execute]
----
oc apply -f ap-dataguard-alarm-policy.yaml
----

. The `ap-logconf.yaml` file creates the Log Profile that specifies the
format of the logs to be generated when the policy detects an attack.

. The `waf.yaml` file creates the WAF configuration that links
the WAF policy and Log Profile to the NGINX Ingress Controller.

== Attach NAP Policy to the NGINX Ingress Controller’s Virtual Server

It is important that the application always has a WAF protecting it.

To enable NAP for an application, a Virtual Server in NGINX Ingress
Controller requires both a Policy and an APPolicy custom resource to be
attached to it. You simply need to add the reference to the Virtual
Server.

*Steps*

. Examine the contents of the *VirtualServer* resource

[source,sh,role=execute]
----
oc get virtualserver arcadia
----

. Update VirtualServer resource
+
When you run `oc edit`, OpenShift automatically detects the changes as soon as you save and exit the editor. It will validate and apply the updated resource immediately.

You can use `vi` commands to make changes to the file

[cols="1,2", options="header"]
|===
| Command | Description

| i       | Enter insert mode
| dd      | Delete current line
| :wq     | Save and quit
| :q!     | Quit without saving
| Esc     | Exit insert mode
|===

[source,sh,role=execute]
----
oc edit virtualserver arcadia
----

. Add the following content to the lines immediately following
[.title-ref]#host: $nginx_ingress#, at the same indentation level. 

+

[source,sh,role=execute]
----
policies:
- name: waf-policy
----

Once modified, your `virtualserver` yml should resemble this:

[source]
----
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: arcadia
spec:
  host: $nginx_ingress
  policies:
  - name: waf-policy
  upstreams:
  - name: arcadia-main
    service: arcadia-main
    port: 80
  - name: arcadia-app2
    service: arcadia-app2
    port: 80
  - name: arcadia-app3
    service: arcadia-app3
    port: 80
----


Save the file and exit the editor.

We are now ready to test our WAF.
